import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {launchBrowser} from '../../../th10_web/scripts/native/browser-launch.mjs';
const output=fileURLToPath(new URL('../../artifacts/sdl-release/verification/',import.meta.url));mkdirSync(output,{recursive:true});
const base='https://api.steinsgateon.com',expected=JSON.parse(readFileSync(new URL('../../artifacts/sdl-release/site/manifest.json',import.meta.url),'utf8'));
const browser=await launchBrowser({timeout:30000,args:['--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']}),context=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true,deviceScaleFactor:2}),page=await context.newPage(),errors=[],failures=[],blockedAnalytics=[],networkWarnings=[];
page.on('pageerror',e=>errors.push(e.stack));page.on('requestfailed',r=>failures.push({url:r.url(),reason:r.failure()}));page.on('console',e=>{if(e.type()==='error'){const text=e.text();if(text.includes('https://static.cloudflareinsights.com/beacon.min.js/')&&text.includes('Content Security Policy'))blockedAnalytics.push(text);else if(/Failed to load resource: the server responded with a status of (502|503|504)/.test(text))networkWarnings.push(text);else errors.push(text);}});
try{
 console.log('Checking public manifest');const response=await context.request.get(base+'/manifest.json',{timeout:25000});assert.equal(response.status(),200);const manifest=await response.json();assert.equal(manifest.game,'th09');assert.equal(manifest.version,expected.version);assert.equal(manifest.execution.sha256,expected.execution.sha256);
 console.log('Opening shared public launcher');await page.goto(base+'/',{waitUntil:'domcontentloaded',timeout:60000});await page.locator('button[data-game=th09]').waitFor();if(await page.locator('#changelogConfirm').isVisible())await page.locator('#changelogConfirm').click();await page.locator('button[data-game=th09]').tap();await page.locator('#launch').tap();
 await page.waitForFunction(()=>document.querySelector('#gameFrame')?.contentWindow?.__th09Runtime,null,{timeout:300000});const game=page.frames().find(f=>f.url().includes('/runtime/th09/th09.html'));assert.ok(game);if(await page.locator('#touchHelpClose').isVisible())await page.locator('#touchHelpClose').tap();
 await game.waitForFunction(()=>__th09Runtime.status().title[0]>30);await game.evaluate(()=>{const c=Module;c._th09_loop_pause(1);const step=n=>{for(let i=0;i<n;i++)if(!c._th09_game_tick(0))throw Error('game tick')};const key=s=>{c._th09_key(s,1);step(1);c._th09_key(s,0);step(16)};key(44);key(44);key(44);c._th09_key(29,1);step(700);c._th09_key(29,0);c._th09_game_draw();});
 const state=await game.evaluate(()=>({status:__th09Runtime.status(),audio:Module.SDL3?.audioContext?.state}));assert.equal(state.status.title[1],0);assert.ok(state.status.session[1]>600);await page.screenshot({path:output+'public-mobile-battle.png'});
 // Verify the tunnel upgrades bounded game-only room traffic; close it immediately.
 const room=await page.evaluate(()=>new Promise((resolve,reject)=>{const ws=new WebSocket('wss://api.steinsgateon.com/netplay'),timer=setTimeout(()=>{ws.close();reject(Error('Network room timeout'));},15000);ws.onopen=()=>fetch('/version.json').then(r=>r.json()).then(v=>ws.send(JSON.stringify({type:'create',build:v.build,unlocked:31,difficulty:1,focus:0})));ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='room'){ws.send(JSON.stringify({type:'leave'}));ws.close();clearTimeout(timer);resolve(m.type);}else if(m.type==='error'){clearTimeout(timer);ws.close();reject(Error(m.message));}};ws.onerror=()=>{clearTimeout(timer);reject(Error('WebSocket upgrade failed'));};}));assert.equal(room,'room');
 const blocked=[];for(const path of ['/th09.exe','/score.dat','/scripts/serve.mjs','/cloudflared-token.txt']){const r=await context.request.get(base+path,{timeout:25000});assert.equal(r.status(),404,path);blocked.push(path);}
 assert.equal(errors.length,0,errors.join('\n'));const report={passed:true,checkedAt:new Date().toISOString(),url:base+'/app/th09.html',originPort:3007,version:expected.version,wasm:expected.execution.sha256,physicalPhone:false,publicResourceDownload:true,websocketUpgrade:true,downloadBytes:expected.downloadBytes,state,blocked,errors,failures,blockedAnalytics,networkWarnings};writeFileSync(output+'deployment.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
}catch(e){await page.screenshot({path:output+'public-failure.png'}).catch(()=>{});writeFileSync(output+'deployment-failure.json',JSON.stringify({error:e.stack,errors,failures,blockedAnalytics,status:await page.locator('#status').textContent().catch(()=>null)},null,2));console.error(e);process.exitCode=1;}
finally{await browser.close();}
