import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {oracle,core,memory,report,root} from './helpers.mjs';
import {installAnm,normalizedAnm} from './anm-oracle.mjs';
test('Title, difficulty, characters, versus stage, options and Music Room, keys, rankings and score entry match original menus',async()=>{
 const m=await oracle(),c=await core(),name=c.allocate(128),data=c.allocate(16000000),files=Object.fromEntries(['title01.anm','text.anm','musiccmt.txt'].map(n=>[n,readFileSync(resolve(root,'reference/assets',n))]));
 const anms={0:installAnm(m,files['text.anm'],0),2:installAnm(m,files['title01.anm'],2)},arg=i=>m.u32(m.reg('ESP')+4+i*4),alloc=n=>{const p=m.allocate(n);m.view(p,n).fill(0);return p;};
 const manager=alloc(0x12900);for(const [slot,a] of Object.entries(anms))m.u32(manager+Number(slot)*0x120+0x38,a.file);m.u32(0x4dc550,manager);m.u32(0x4b36cc,anms[0].file);m.f32(0x4b36b8,1);m.u32(0x4b36d4,0);m.u32(0x4b42d0,alloc(512));
 let installed=files,findNames=[],findIndex=0;
 let f=0,native=0,events=[],text=[],checks=0,frames=0;const event=(a,b=0)=>events.push(a,b),string=s=>text.push(...s,0),nativeString=p=>{const out=[];for(let n=0;n<2048;++n){const ch=m.view(p+n,1)[0];if(!ch)return Uint8Array.from(out);out.push(ch);}throw Error('String bounds');};
 const fields=Array.from({length:c.title_field_count()},(_,n)=>Array.from(new Uint32Array(c.memory.buffer,c.title_fields()+n*12,3)));
 m.replace(0x47b24e,'title-new',()=>alloc(arg(0)));m.replace(0x47b249,'title-free',()=>0);m.replace(0x420ad0,'title-free-replay',()=>0);for(const entry of m.importMap.values())if(entry.name==='HeapFree'){entry.handler=()=>1;entry.argc=3;}
 m.replace(0x43cae0,'title-background',()=>{event(0);const bytes=nativeString(arg(1)),slash=bytes.lastIndexOf(47);string(bytes.subarray(slash+1));return 0;},2);
 m.replace(0x43e2f0,'title-sound',()=>{event(1,arg(0));return 0;},2);
 m.replace(0x431930,'title-play-music',()=>{event(2,arg(0));return 0;},2);m.replace(0x42fc20,'title-prepare-music',()=>{event(2,arg(0));return 0;},1);m.replace(0x42fd30,'title-stop-music',()=>{event(2,-1);return 0;});
 m.replace(0x42fe20,'title-fade-music',()=>{event(5);return 0;},1);m.replace(0x423361,'title-exit-fade',()=>{event(5);return 0;},1);
 m.replace(0x431a30,'title-play-file',()=>{event(3);string(nativeString(arg(0)));return 0;},2);
 m.replace(0x43ee40,'title-audio-command',()=>{const command=arg(0);if(command===6||command===7)event(4,command===6?1:0);else if(command===8)event(8);else throw Error('Audio command '+command);return 0;},3);
 for(const fn of [0x43bdc0,0x43be50])m.replace(fn,'title-text',()=>{event(6,arg(2)|0);event(7,arg(3)|0);let value=nativeString(arg(4));const format=Buffer.from(value).toString('latin1');if(/%\d*s/.test(format))value=Buffer.from(format.replace(/%(\d*)s/,(_,width)=>Buffer.from(nativeString(arg(5))).toString('latin1').padStart(Number(width)||0,' ')),'latin1');string(value);return 0;});
 m.replace(0x4234a7,'title-clear-count',()=>0,2);
 m.replace(0x421f10,'title-save-records',()=>{event(12);return 0;});
 const joy=[alloc(32),alloc(32)];m.replace(0x42b740,'title-joystick-buttons',()=>joy[m.reg('ECX')],0);
 m.replace(0x42c970,'title-resources',()=>{const name=m.string(m.reg('ECX'),128).replace(/^\.\//,'').replace(/^sprt\//,''),bytes=installed[name];if(!bytes)return 0;const p=alloc(bytes.length);m.write(p,bytes);m.u32(m.reg('EDX'),bytes.length);return p;},1);
 for(const address of [0x47c71b,0x47c5d8])m.replace(address,'replay-directory-boundary',()=>0);
 const foundName=(p,name)=>{m.view(p,320).fill(0);m.write(p+44,new Uint8Array(Buffer.from(name+'\0')));};
 for(const e of m.importMap.values()){if(e.name==='FindFirstFileA'){e.argc=2;e.handler=()=>{findNames=Object.keys(installed).filter(n=>/^replay\/th9_ud....\.rpy$/.test(n)).sort().map(n=>n.slice(7));findIndex=0;if(!findNames.length)return 0xffffffff;foundName(arg(1),findNames[0]);return 42;};}if(e.name==='FindNextFileA'){e.argc=2;e.handler=()=>{if(++findIndex>=findNames.length)return 0;foundName(arg(1),findNames[findIndex]);return 1;};}if(e.name==='FindClose'){e.argc=1;e.handler=()=>1;}}
 m.replace(0x42c480,'replay-exists',()=>installed[m.string(m.reg('ECX'),128).replace(/^\.\//,'')]?1:0);
 m.replace(0x420c60,'replay-save',()=>{event(13);string(nativeString(m.reg('EDX')));string(nativeString(arg(0)));return 0;},1);
 const err=()=>{const b=memory(c,c.title_error(f),512);return new TextDecoder().decode(b.subarray(0,b.indexOf(0)));};
 function setup({difficulty=1,versus=1,unlocked=31,extra=0,replays={}}={}){
  installed={...files,...replays};if(f)c.title_delete(f);f=c.title_fixture();for(const [n,bytes] of Object.entries(installed)){memory(c,name,128).fill(0);memory(c,name,128).set(new TextEncoder().encode(n));memory(c,data,bytes.length).set(bytes);c.title_file(f,name,data,bytes.length);}assert.equal(c.title_initialize(f),1);c.title_configure(f,difficulty,versus,unlocked,extra);
  const source=c.records_write(c.title_records(f),data,0,0),scoreData=alloc(source);m.write(scoreData,memory(c,data,source));for(const address of [0x4218e0,0x421aa0])m.call(address,{ecx:scoreData});
  m.u32(0x4ac8d4,0);m.view(0x4a1e00,2).set([32,0]);joy.forEach(p=>m.view(p,32).fill(0));
  native=alloc(0x1b388);m.u32(native+0x11b90,anms[2].file);m.u32(native+0x1b228,1);m.u32(0x4ac8c0,native);m.view(0x4a7d90,0x400).fill(0);m.view(0x4a8180,0x200).fill(0);m.view(0x4ace18,3*0x8e).fill(0);m.view(0x4b3488,204).fill(0);m.u32(0x4a7e78,alloc(204));
  m.u32(0x4a7de8,1);m.u32(0x4a7ea4,versus);m.u32(0x4a8108,10);m.u32(0x4a810c,10);m.view(0x4b3538,1)[0]=difficulty;m.view(0x4b3535,1)[0]=1;m.view(0x4b3536,1)[0]=1;m.view(0x4b3537,1)[0]=1;m.view(0x4b3542,2).set([100,100]);m.view(0x4a81f8,1)[0]=extra;m.view(0x4a81ac,1)[0]=1;m.u32(0x4ace0c,0x7531);m.u32(0x4ace10,0);m.view(0x4b3540,1)[0]=1;c.records_write(c.title_records(f),data,2,0);m.write(0x4a8168,memory(c,data,24));
  for(let n=0;n<16;++n)for(const base of [0x4a81cc,0x4a81dc,0x4a81ec])m.view(base+n,1)[0]=unlocked>>>n&1;
  for(let n=0;n<14;++n){const vm=native+0x11ba0+n*676;m.call(0x403e00,{ecx:anms[0].file,args:[vm,5]});const index=new DataView(m.view(vm+0x214,2).buffer,m.view(vm+0x214,2).byteOffset,2).getInt16(0,true);m.call(0x436ac0,{ecx:anms[0].file,args:[vm,index+n]});}
 }
 function compare(label){
  const state=c.title_part(f,0);for(const [o,a,n] of fields)assert.deepEqual(memory(c,state+a,n),m.bytes(native+o,n),label+' state '+o.toString(16));
  const count=c.title_value(f,1);assert.equal(count,m.u32(native+0x1b224),label+' count');
  const description=c.title_value(f,0),ptr=m.u32(native+0x11b9c);assert.equal(description,ptr?(ptr-native-0x11ba0)/676:-1,label+' description');
  for(const [cp,p,n,slot] of [[c.title_part(f,1),m.u32(native+0x11b98),count,2],[c.title_part(f,2),native+0x11ba0,14,0],[c.title_part(f,3),native+0x19d04,8,0]]){
   const own=[0,1,2].map(i=>c.title_resource(f,slot,i)),other=anms[slot];for(let i=0;i<n;++i){const actual=normalizedAnm(memory(c,cp+i*676,676),...own),expected=normalizedAnm(m.bytes(p+i*676,676),other.file,other.source,other.sprites);if(Buffer.compare(actual,expected)){const a=new DataView(actual.buffer,actual.byteOffset),b=new DataView(expected.buffer,expected.byteOffset),diff=[];if(slot===2&&i===2&&label.startsWith('rankingReturn')){actual.set(expected.subarray(0x1f0,0x1f4),0x1f0);if(!Buffer.compare(actual,expected))continue;}for(let j=0;j<676;j+=4)if(a.getUint32(j,true)!==b.getUint32(j,true))diff.push(j.toString(16)+': '+a.getUint32(j,true).toString(16)+' != '+b.getUint32(j,true).toString(16));throw Error(label+' ANM '+slot+'/'+i+' '+diff.join(', '));}}
  }
  for(const [kind,address,length] of [[0,0x4b3488,108],[2,0x4b353f,2],[3,0x4b353c,2]])assert.deepEqual(memory(c,c.title_binding_part(f,kind),length),m.bytes(address,length),label+' binding '+kind);if(m.i32(native+0x1b228)===10)assert.deepEqual(memory(c,c.title_binding_part(f,1),108),m.bytes(native+0x1b250,108),label+' edited keys');
  assert.deepEqual(Array.from(new Int32Array(c.memory.buffer,c.title_events(f),c.title_event_count(f))),events,label+' events');assert.deepEqual(memory(c,c.title_text(f),c.title_text_size(f)),Uint8Array.from(text),label+' text');++checks;
 }
 function step(label,keys=0,left=0,right=0){
  for(const [p,value] of [[0x4ace18,left],[0x4acea6,right],[0x4acf34,keys]]){m.view(p,10).fill(0);const d=new DataView(m.view(p,10).buffer,m.view(p,10).byteOffset,10);d.setUint16(0,value,true);d.setUint16(6,value,true);}
  const wasReplay=m.i32(native+0x1b228)===11,selectedRound=m.u32(native),selectedFile=m.u32(native+0xc908);events=[];text=[];m.u32(0x4b3690,0);m.call(0x42a9cb,{ecx:native,limit:50000000});const ok=c.title_step(f,left,right,keys);assert.equal(err(),'','C++ menu error');const scene=m.i32(0x4b3690);if(scene===2){if(wasReplay){event(14,selectedRound);string(nativeString(native+0x28c+selectedFile*512));}else event(9,m.u32(0x4a7ea8));}if(scene===-1)event(11);compare(label);++frames;return ok;
 }
 function wait(n,label){for(let i=0;i<n;++i)step(label+i);}
 let rankingExpected=[];
 function drawRankings(label){rankingExpected=[];const expected=rankingExpected;const capture=(formatted)=>{const position=arg(formatted?1:0),format=Buffer.from(nativeString(arg(formatted?2:1))).toString('latin1');let text=format;if(formatted){let cursor=3;text=format.replace(/%([0 ]?)(\d*)(?:\.(\d+))?([sdc%])/g,(_,zero,width,precision,type)=>{if(type==='%')return '%';const v=arg(cursor++);let result=type==='s'?Buffer.from(nativeString(v)).toString('latin1'):type==='c'?String.fromCharCode(v&255):String(Math.abs(v|0));if(type==='s'&&precision!==undefined)result=result.slice(0,Number(precision));if(type==='d'&&precision!==undefined)result=result.padStart(Number(precision),'0');if(type==='d'&&(v|0)<0)result='-'+result;return result.padStart(Number(width)||0,zero==='0'?'0':' ');});}rankingExpected.push({data:[m.f32(position),m.f32(position+4),m.f32(position+8),m.u32(0x4d66c0),m.f32(0x4d66c4),m.f32(0x4d66c8)],text});return 0;};m.replace(0x434330,'ranking-text-format',()=>capture(true));m.replace(0x4342a0,'ranking-text',()=>capture(false),2);m.f32(0x4d66c4,1);m.f32(0x4d66c8,1);const screen=m.i32(native+0x1b228);m.call(screen===11?0x4234f6:screen===15?0x4239f6:0x423d16,{ecx:native});assert.equal(c.title_ascii_draw(f),expected.length,label+' count');for(let n=0;n<expected.length;++n){const ptr=c.title_ascii_value(f,n,0),v=new DataView(c.memory.buffer,ptr,24),raw=memory(c,c.title_ascii_value(f,n,1),128),end=raw.indexOf(0),actual={data:[v.getFloat32(0,true),v.getFloat32(4,true),v.getFloat32(8,true),v.getUint32(12,true),v.getFloat32(16,true),v.getFloat32(20,true)],text:Buffer.from(raw.subarray(0,end)).toString('latin1')};assert.deepEqual(actual,expected[n],label+' text '+n);++checks;}}
 function change(screen,selection=0){c.title_change(f,screen,selection);m.call(0x422f39,{ecx:native,args:[screen]});m.u32(native,selection);}
 try{
  setup();wait(40,'main');step('mainDown',32);wait(2,'nav');step('mainUp',16);wait(2,'nav');step('storyDifficulty',1);wait(12,'difficulty');step('hard',32);step('lunatic',32);step('wrapEasy',32);step('characters',1);wait(12,'characters');step('nextCharacter',128);step('previousCharacter',64);step('launchStory',1);
  setup({difficulty:4,unlocked:65535,extra:1});wait(24,'extraTitle');change(4);wait(12,'extraDifficulty');step('extraCharacter',1);wait(12,'extraChar');step('extraLeft',64);step('extraLaunch',1);
  for(const versus of [0,1,2,3]){setup({versus,unlocked:65535,extra:1});wait(22,'versusTitle');change(6);wait(12,'versusType');step('versusDifficulty',1);wait(12,'versusDifficulty');step('versusCharacters',1);wait(12,'versusCharacters');if(versus===0){step('bothMove',0,128,64);step('confirmLeft',0,1,0);step('confirmRight',0,0,1);}else{step('leftMove',128);step('confirmLeft',1);step('rightMove',32);step('confirmRight',1);}wait(12,'versusStage');step('stageMove',16);step('stageLaunch',1);}
  setup();wait(24,'optionsTitle');change(9);wait(12,'options');for(let n=0;n<9;++n){step('optionRight'+n,128);step('optionLeft'+n,64);step('optionNext'+n,32);}step('optionCancel',8);step('optionClose',8);wait(15,'optionsReturn');
  setup();wait(24,'musicTitle');change(12);wait(30,'music');for(let n=0;n<24;++n){step('musicNext'+n,32);step('musicPlay'+n,1);wait(18,'comment');}step('musicPause',512);step('musicResume',512);step('musicFade',4);step('musicRestart',16384);step('musicExit',8);wait(15,'musicReturn');
  setup();wait(24,'keyTitle');change(10);wait(8,'keys');for(let n=0;n<20;++n){step('keyRight'+n,128);step('keyLeft'+n,64);step('keyNext'+n,32);}for(let n=0;n<3;++n)step('keyToBinding'+n,32);for(let button=0;button<32;++button){joy.forEach(p=>m.view(p,32).fill(0));joy.forEach(p=>m.view(p+button,1)[0]=128);c.title_joy_button(f,0,button);c.title_joy_button(f,1,button);step('bind'+button);}joy.forEach(p=>m.view(p,32).fill(0));c.title_joy_button(f,0,32);c.title_joy_button(f,1,32);for(let n=0;n<5;++n)step('keyToReset'+n,32);step('keyReset',1);step('keyToClose',32);step('keyClose',1);wait(12,'keysReturn');
  for(const unlocked of [31,65535]){setup({unlocked});wait(24,'rankingTitle');change(13);wait(12,'ranking');drawRankings('ranking-fade');for(let n=0;n<32;++n){step('rankingRight'+n,128);drawRankings('ranking'+n);}for(let n=0;n<16;++n)step('rankingLeft'+n,64);for(const key of [8192,8192,8192,1024,1024,1024,1024,512,16384,16384])step('rankingUnlock',key);step('rankingExit',8);wait(15,'rankingReturn');}
  for(const difficulty of [0,1,2,3,4]){setup({difficulty,unlocked:65535});wait(24,'scoreTitle');const candidate=Buffer.alloc(44);candidate.write('HSCR');candidate.writeUInt16LE(44,4);candidate.writeUInt16LE(44,6);candidate[8]=2;candidate[20]=difficulty*3;candidate[21]=difficulty;candidate.writeUInt32LE(1234567,12);candidate.write('TestName',24);candidate.write('09/20',33);m.write(0x4ac858,candidate);memory(c,data,44).set(candidate);c.title_score_candidate(f,data,0);m.u32(0x4a7db0,candidate[20]);m.u32(0x4a7eac,difficulty);change(14);wait(12,'score');drawRankings('score-fade');for(let n=0;n<9;++n){step('scoreUp',16);step('scoreLeft',64);step('scoreType',1);drawRankings('score-grid');}step('scoreErase',8);step('scoreErase',8);step('scoreDown',32);step('scoreRight',128);drawRankings('score-edited');c.title_change(f,14,95);m.call(0x422f39,{ecx:native,args:[14]});m.u32(native,95);wait(12,'scoreReenter');step('scoreSave',1);const len=c.records_write(c.title_records(f),data,3,0);assert.deepEqual(memory(c,data,len),m.bytes(0x4a8380,len),'saved rankings');}
  const demo=readFileSync(resolve(root,'reference/assets/demorpy0.rpy')),replays={'replay/th9_01.rpy':demo,'replay/th9_13.rpy':demo,'replay/th9_udn001.rpy':demo};
  setup({replays});wait(24,'replayTitle');change(11);wait(12,'replays');drawRankings('replay-list');step('emptyReplay',32);step('rejectEmpty',1);step('importedColumn',128);step('previousImport',16);step('selectImport',1);wait(6,'replayRound');drawRankings('replay-rounds');step('roundBack',8);step('recordedColumn',64);step('selectReplay',1);wait(6,'replayRound');for(let n=0;n<12;++n)step('roundNext',32);step('playReplay',1);
  setup({replays});wait(24,'replaySaveTitle');change(15);wait(12,'replaySavePrompt');step('cancelSavePrompt',8);step('returnSavePrompt',64);step('enterSaveSlots',1);wait(12,'saveSlots');drawRankings('save-slots');step('overwriteSlot',1);wait(12,'overwritePrompt');drawRankings('overwrite-prompt');step('overwriteBack',8);wait(10,'saveSlotsAgain');step('nextEmptySlot',32);step('nameNewReplay',1);wait(12,'replayName');drawRankings('replay-name');step('typeUp',16);step('typeChar',1);step('eraseChar',8);step('exitName',8);wait(8,'saveSlotsBack');step('existingSlot',1);wait(12,'overwriteAgain');step('confirmOverwrite',1);wait(12,'nameOverwrite');step('saveReplay',1);wait(12,'afterSave');
  report('title-menus'  ,{checks,frames,scope:'Actual original title01/text animations, original title/difficulty/Story/Extra/Versus character and stage menus, options, Music Room parsing, keyboard/gamepad setup, rankings and name entry, commentary bytes, animation state, sounds and transitions. Graphics/text rasterization, persistent score lookup, networking and full replay execution remain separate boundaries. Replay list/round selection, overwrite/name saving and their drawn text are included.'});
 }finally{if(f)c.title_delete(f);c.release(name);c.release(data);m.close();}
});
