import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {resolve} from 'node:path';import {core,memory,root,report} from './helpers.mjs';
import {validateMotionReplay,exportReplayName,importReplayName} from '../../sdl-runtime/motion-replay.mjs';
test('Continuous touch round-trips both TH09 players through replay with native keys unchanged',async()=>{const c=await core(),f=c.session_create(),name=c.allocate(128),data=c.allocate(16000000),out=c.allocate(16000000);let checks=0;
for(const n of readdirSync(resolve(root,'reference/assets')).filter(n=>/\.(anm|sht|ecl|msg|std|bmp|png|jpg)$/.test(n))){const b=readFileSync(resolve(root,'reference/assets',n));memory(c,name,128).fill(0);memory(c,name,128).set(new TextEncoder().encode(n));memory(c,data,b.length).set(b);c.session_file(f,name,data,b.length);}
// Replay flag/call counter are bookkeeping. CPU keyboard input is deliberately
// not stored by the native format; gameplay motion/state remains compared.
let twoHumans=false;
const snap=()=>Array.from(new Int32Array(c.memory.buffer,c.session_snapshot(f),48)).map((v,i)=>i===2?v&~8:v).filter((_,i)=>i!==1&&(twoHumans||![36,37].includes(i)));
try{for(const mode of [0,2,3]){twoHumans=mode===3;assert.equal(twoHumans?c.session_begin_human(f,12345):c.session_begin(f,0,mode,1,12345),1);const states=[];for(let n=0;n<1800&&c.session_value(f,0)===1;n++){const k=n<200?257:n%6<3?1:0;for(let s=0;s<2;s++)c.session_motion(f,s,+(n>200&&n%17!==0),Math.sin(n*.025+s)*1.9,Math.cos(n*.031+s)*1.1);assert.equal(c.session_step(f,k,k,k),1);states.push(snap());}
memory(c,name,128).fill(0);memory(c,name,128).set(new TextEncoder().encode('TOUCH'));const size=c.session_save(f,name,out,16000000),bytes=Uint8Array.from(memory(c,out,size));assert.ok(validateMotionReplay(bytes,9));assert.equal(exportReplayName('th9_01.rpy',bytes,9),'th9_01.rpyx');assert.equal(importReplayName('th9_01.rpyx',bytes,9),'th9_01.rpy');const bad=bytes.slice();bad[bad.length-30]^=1;assert.throws(()=>validateMotionReplay(bad,9));memory(c,data,size).set(bytes);assert.equal(c.session_play(f,data,size,mode>=2?9:0),1);for(let n=0;n<states.length;n++){assert.equal(c.session_step(f,0,0,0),1);assert.deepEqual(snap(),states[n],mode+' frame '+n);checks++;}}
report('touch-replay',{checks});}finally{c.session_delete(f);c.release(name);c.release(data);c.release(out);}});
